
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      path: /h2-test
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  # H2 메모리 DB를 사용하기 위한 설정
  datasource:
    url: jdbc:h2:mem:testdb




property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c

fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green